"""empty message

Revision ID: 31117d671850
Revises: 7d744968f1ad
Create Date: 2023-11-12 22:35:30.558494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31117d671850'
down_revision = '7d744968f1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
